/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as FlagsIndexRouteImport } from './routes/flags.index'
import { Route as FlagsFlagIdRouteImport } from './routes/flags.$flagId'
import { Route as FlagsNewRouteImport } from './routes/flags.new'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsIndexRoute = FlagsIndexRouteImport.update({
  id: '/flags/',
  path: '/flags/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsFlagIdRoute = FlagsFlagIdRouteImport.update({
  id: '/flags/$flagId',
  path: '/flags/$flagId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsNewRoute = FlagsNewRouteImport.update({
  id: '/flags/new',
  path: '/flags/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/environments': typeof EnvironmentsRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/flags/$flagId': typeof FlagsFlagIdRoute
  '/flags/new': typeof FlagsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/flags/': typeof FlagsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/environments': typeof EnvironmentsRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/flags/$flagId': typeof FlagsFlagIdRoute
  '/flags/new': typeof FlagsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/flags': typeof FlagsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/environments': typeof EnvironmentsRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/flags/$flagId': typeof FlagsFlagIdRoute
  '/flags/new': typeof FlagsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/flags/': typeof FlagsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/environments'
    | '/login'
    | '/overview'
    | '/settings'
    | '/signup'
    | '/flags/$flagId'
    | '/flags/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/flags/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/environments'
    | '/login'
    | '/overview'
    | '/settings'
    | '/signup'
    | '/flags/$flagId'
    | '/flags/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/flags'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/environments'
    | '/login'
    | '/overview'
    | '/settings'
    | '/signup'
    | '/flags/$flagId'
    | '/flags/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/flags/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  FlagsFlagIdRoute: typeof FlagsFlagIdRoute
  FlagsNewRoute: typeof FlagsNewRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  FlagsIndexRoute: typeof FlagsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags/': {
      id: '/flags/'
      path: '/flags'
      fullPath: '/flags/'
      preLoaderRoute: typeof FlagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags/$flagId': {
      id: '/flags/$flagId'
      path: '/flags/$flagId'
      fullPath: '/flags/$flagId'
      preLoaderRoute: typeof FlagsFlagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags/new': {
      id: '/flags/new'
      path: '/flags/new'
      fullPath: '/flags/new'
      preLoaderRoute: typeof FlagsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  FlagsFlagIdRoute: FlagsFlagIdRoute,
  FlagsNewRoute: FlagsNewRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  FlagsIndexRoute: FlagsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
